function About() {
  return (
    <div>
      <h1>About Service Line Markers</h1>

      <section style={{ marginBottom: '2rem' }}>
        <h2>Architecture: Pages for Hosting, Actions for Backend</h2>
        <p>
          This application demonstrates a modern serverless architecture using GitHub Pages for static hosting
          and GitHub Actions for backend processing. No traditional server or database is required.
        </p>

        <h3>How It Works</h3>
        <ol>
          <li><strong>Static Frontend:</strong> React SPA deployed to GitHub Pages</li>
          <li><strong>Data Fetching:</strong> Scheduled/on-demand GitHub Actions fetch from public APIs</li>
          <li><strong>Data Storage:</strong> JSON files committed back to repository</li>
          <li><strong>Automatic Updates:</strong> Site reflects changes immediately after commits</li>
        </ol>

        <pre style={{
          background: '#f8f9fa',
          padding: '1rem',
          borderRadius: '4px',
          overflow: 'auto',
          fontSize: '0.875rem'
        }}>
{`Frontend (GitHub Pages)
├── index.html
├── static assets
└── /data/*.json (generated by Actions)

Backend (GitHub Actions)
├── .github/workflows/data-sync.yml
├── scripts/fetch-data.mts
└── Automated commits to main`}
        </pre>
      </section>

      <section style={{ marginBottom: '2rem' }}>
        <h2>Design System</h2>
        <p>
          The service-line marker design system provides configurable visual tokens for mapping applications.
          Features include multiple marker variants, colorblind-safe palettes, and level-of-detail switching.
        </p>

        <h3>Key Features</h3>
        <ul>
          <li>7 marker variants (split, nested, donut, hex, halo, band, pin)</li>
          <li>3 color palettes (Okabe-Ito, ColorBrewer Dark2, Monochrome)</li>
          <li>Level-of-detail switching based on zoom level</li>
          <li>Accessibility-first with WCAG AA compliance</li>
          <li>Integration examples for Mapbox GL, Leaflet, and deck.gl</li>
        </ul>
      </section>

      <section style={{ marginBottom: '2rem' }}>
        <h2>Deployment</h2>
        <h3>GitHub Pages Setup</h3>
        <ol>
          <li>Enable GitHub Pages in repository settings</li>
          <li>Set source to "GitHub Actions"</li>
          <li>Push to main branch to trigger deployment</li>
          <li>Optional: Add custom domain via CNAME file</li>
        </ol>

        <h3>Preview Deployments</h3>
        <p>
          Pull requests automatically create preview deployments. Check the "Deployments" tab
          in GitHub to view live previews before merging.
        </p>
      </section>

      <section>
        <h2>Development</h2>
        <h3>Local Setup</h3>
        <pre style={{
          background: '#f8f9fa',
          padding: '1rem',
          borderRadius: '4px',
          overflow: 'auto',
          fontSize: '0.875rem'
        }}>
{`npm install
npm run dev`}
        </pre>

        <h3>Available Scripts</h3>
        <ul>
          <li><code>npm run dev</code> - Start development server</li>
          <li><code>npm run build</code> - Build for production</li>
          <li><code>npm run test</code> - Run unit tests</li>
          <li><code>npm run lint</code> - Run ESLint</li>
          <li><code>npm run a11y</code> - Run accessibility tests</li>
        </ul>
      </section>
    </div>
  )
}

export default About