name: Geocode Addresses

on:
  workflow_dispatch:
    inputs:
      batch_size:
        description: 'Number of addresses to geocode per batch'
        required: false
        default: '100'
        type: string
      delay_ms:
        description: 'Delay between requests in milliseconds'
        required: false
        default: '500'
        type: string

jobs:
  geocode:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install GDAL
      run: sudo apt-get update && sudo apt-get install -y gdal-bin unzip

    - name: Install Tippecanoe
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
        sudo apt-get update
        sudo apt-get install -y tippecanoe

    - name: Install dependencies
      run: npm ci

    - name: Run Census geocoding script
      run: npm run geocode:nys

    - name: Generate PMTiles
      run: npm run generate:pmtiles

    - name: Copy geocoded data to public
      run: cp data/markers.json public/data/markers.json

    - name: Commit geocoded results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/markers.json public/data/markers.json data/service-lines.geojson public/tiles/service-lines.pmtiles
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update geocoded coordinates and PMTiles using NYS GIS data"
          git push https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
        fi